export const TABS = {
  // Admin
  ADMIN_ORGANIZATION_UNITS: 'ADMIN_ORGANIZATION_UNITS',
  ADMIN_USERS: 'ADMIN_USERS',
  ADMIN_ROLES: 'ADMIN_ROLES',
  ADMIN_AUDIT_LOGS: 'ADMIN_AUDIT_LOGS',
  ADMIN_LANGUAGE: 'ADMIN_LANGUAGE',
  ADMIN_UI_CUSTOMIZATION: 'ADMIN_UI_CUSTOMIZATION',
  ADMIN_HOST_SETTINGS: 'ADMIN_HOST_SETTINGS',
  ADMIN_TENANT_SETTINGS: 'ADMIN_TENANT_SETTINGS',

  // Master
  MASTER_BTS_SYSTEM_PARAM: 'MASTER_BTS_SYSTEM_PARAM',
  MASTER_BTS_COUNTRY_DESTINATION: 'MASTER_BTS_COUNTRY_DESTINATION',
  MASTER_BTS_TITLE_GROUP: 'MASTER_BTS_TITLE_GROUP',
  MASTER_BTS_BUSINESS_TRIP_POLICY: 'MASTER_BTS_BUSINESS_TRIP_POLICY',
  MASTER_BTS_BUDGET: 'MASTER_BTS_BUDGET',
  MASTER_BTS_INVOICING: 'MASTER_BTS_INVOICING',
  MASTER_BTS_AIR_TICKET: 'MASTER_BTS_AIR_TICKET',
  MASTER_BTS_HOTEL: 'MASTER_BTS_HOTEL',
  MASTER_BTS_ORACLE_INVOICE_BATCH_NAME: 'ASTER_BTS_ORACLE_INVOICE_BATCH_NAME',
  MASTER_BTS_DAILY_EXCHANGE_RATES: 'MASTER_BTS_DAILY_EXCHANGE_RATES',
  MASTER_BTS_VISA: 'MASTER_BTS_VISA',
  MASTER_BTS_TIME_KEEPER: 'MASTER_BTS_TIME_KEEPER',

  INF_FQF3BT01: 'INF_FQF3BT01',
  INF_FQF3BT03: 'INF_FQF3BT03',

  // One day
  ONEDAY_APPROVAL: 'ONEDAY_APPROVAL',
  ONEDAY_APPROVAL_DETAIL: 'ONEDAY_APPROVAL_DETAIL',
  ONEDAY_EXPENSE_DECLARATION: 'ONEDAY_EXPENSE_DECLARATION',
  ONEDAY_EXPENSE_DECLARATION_DETAIL: 'ONEDAY_EXPENSE_DECLARATION_DETAIL',

  //Overnight
  OVERNIGHT_APPROVAL: 'OVERNIGHT_APPROVAL',
  OVERNIGHT_EXPENSE_DECLARATION: 'OVERNIGHT_EXPENSE_DECLARATION',
  OVERNIGHT_EXPENSE_DECLARATION_DETAIL: 'OVERNIGHT_EXPENSE_DECLARATION_DETAIL',
  OVERNIGHT_EXPENSE_LATE: 'OVERNIGHT_EXPENSE_LATE',
  OVERNIGHT_WIFI_DEVICE_PRE_REQUEST: 'BTS_WIFI_DEVICE_PRE_REQUEST',
  OVERNIGHT_APPROVAL_DETAIL: 'OVERNIGHT_APPROVAL_DETAIL',

  //FIN
  FIN_ADVANCE_PAYMENT: 'FIN_ADVANCE_PAYMENT',
  FIN_AIR_TICKET: 'FIN_AIR_TICKET',
  FIN_BUDGET_CHECKING: 'FIN_BUDGET_CHECKING',
  FIN_EXPENSE_PAYMENT: 'FIN_EXPENSE_PAYMENT',
  FIN_INVOICING: 'FIN_INVOICING',
  FIN_HOTEL: 'FIN_HOTEL',
  FIN_IMPORT_TO_HRM : 'FIN_IMPORT_TO_HRM',
  //GA

  //GA_AIR_TICKET: 'GA_AIR_TICKET',
  GA_AIR_TICKET_REQUEST: 'GA_AIR_TICKET_REQUEST',
  GA_INFO: 'GA_INFO',
  GA_EXPECTED_AIR_TICKET: 'GA_EXPECTED_AIR_TICKET',
  GA_HOTEL: 'GA_HOTEL',

  //HR
  HR_AIR_TICKET_ICT: 'HR_AIR_TICKET_ICT',

  //IT
  IT_WIFI_DEVICE_REQUEST: 'IT_WIFI_DEVICE_REQUEST',
  WIFI_DEVICE_REQUEST: 'WIFI_DEVICE_REQUEST',

  //DOWLOAD
  DOWLOAD: 'DOWLOAD',

  //FAQ
  FAQ: 'FAQ',

  //TimerKeeper
  TIMER_KEEPER: 'TIMER_KEEPER',


  //REPORT
  REPORT: 'REPORT',
  EXPENSE_REPORT: 'EXPENSE_REPORT',

  //DASHBOARD
  DASHBOARD: 'DASHBOARD',

  //dashboardFin
  FIN_DASHBOARDFIN: 'FIN_DASHBOARDFIN',

  //Interface
  FQF3BT01: 'FQF3BT01',
  FQF3BTLV2: 'FQF3BTLV2',
};
